#########################################################################
##### GOA Dynamics Working Group                                    #####
##### Benthic Nearshore Group - Data Assembly script                #####
##### Created by Rachael Blake on Sept. 21, 2015                    #####
#########################################################################

## load packages (order matters)
library(httr)
library(plyr)
library(dplyr)
library(XML)
library(curl)
library(rvest)
library(tidyr)
library(stringr)


## Steps for adding data columns:
## 1) run each data cleaning script to generate data frames
## 2) create empty data frame
## 3) merge all data frames with CoPrct dataframe:   
##        CoPrct=merge(CoPrct,newData,all.x=T)  


# Source and run each data cleaning script
sourceDir <- function(path, trace=TRUE) {
    for (nm in list.files(path, pattern = "[.][RrSsQq]$")) {
       if(trace) cat(nm,":")
       source(file.path(path, nm))
       if(trace) cat("\n")
    }
}

sourceDir("Benthic_Nearshore_Drivers\Data_Cleaning_Scripts_DMX_Benthic_Nearshore")


# Create empty data frame with Year column
BenNear <- data.frame('Year'=c(1975:2015))


# Merge in data columns generated by data cleaning scripts into one large data frame
BenNear <- merge(BenNear,ENSO_annual,all.x=T)    # ENSO annual
BenNear <- merge(BenNear,pdo_annual,all.x=T)     # PDO annual
BenNear <- merge(BenNear,npgo_annual,all.x=T)    # NPGO annual
BenNear <- merge(BenNear,upanom,all.x=T)         # Upwelling anomalies annual
BenNear <- merge(BenNear,Phy,all.x=T)            # Phytoplankton - Seward Line, spring
BenNear <- merge(BenNear,SatChl_df,all.x=T)      # Chla - Satellite annual
BenNear <- merge(BenNear,SST,all.x=T)            # SST - Seward Line
  



# Optional: Write data frame to a CSV
#write.csv(BenNear, file = "BenNear.csv", row.names=FALSE)



##############################################################################################









