---
title: ' Data Visualizations for DMX Benthic Nearshore Drivers'
author: "Rachael Blake"
date: "January 28, 2016"
output: html_document
---


```{r, echo=FALSE, include=FALSE}

# load necessary packages
library(knitr)
library(httr)
library(plyr)
library(dplyr)
library(XML)
library(curl)
library(rvest)
library(tidyr)
library(stringr)

 dir_dmx_d = c('rblake'='C:/Users/rblake/Documents/NCEAS/GoA Dynamics WG/dmx-drivers'
              # collobrators enter your Sys.info()["user"] and local filepaths to our dmx-drivers repo
              )[Sys.info()["user"]]


```


```{r, echo=FALSE, include=FALSE}
# source(file.path(dir_dmx_d, 
#                  "Benthic_Nearshore_Drivers/Benthic_Nearshore_Data_.R"))

BenNearxx <- read.csv("C:/Users/rblake/Documents/NCEAS/GoA Dynamics WG/dmx-drivers/BenthicNearshore_MusselQuestData.csv")

BenNear <- BenNearxx
```
 
```{r, echo=FALSE, include=FALSE}
BenNear2 <- BenNear %>%
            select(-Quadrat, -Lat,-Long) %>%
          #  mutate_each(funs(as.numeric), Otter_Abun_est) %>%
            group_by(Year, Region, Site_Name) %>%
            summarize_each(funs(sum)) %>%
            ungroup()  
            
```

```{r, echo=FALSE, include=FALSE}
# load some more packages that were creating conflicts with reading in the data
library(reshape2)
library(ggplot2)
library(scales)
library(psych)
library(rworldmap)
library(rworldxtra)
library(rgdal)
```


```{r, echo=FALSE, include=FALSE}
###Map of Regions & Sites

BenNear1 <- BenNear %>%
            filter(Region %in% c("WPWS","KATM","KEFJ"), 
                    !(Site_Name %in% c("Northwest Bay", "Herring Bay-Southwest", "Herring Bay-Bear Cove",
                                       "Ninagiak Island", "Disk Island"))) %>%
            mutate(Region_Site = paste(Region, Site_Name, sep=":"))
# state:
state <- readOGR(dsn=(file.path(dir_dmx_d, "Benthic_Nearshore_Drivers")), layer="statep010")
stateDf <- fortify(state)

# GAK1: 
GAK1_loc <- data.frame(lat=59.85, long= -149.5)
# Station 46060 West Orca Bay
WOB <- data.frame(lat=60.584, long= -146.805)
# Station 46077 Shelikof Strait
SS <- data.frame(lat=57.892, long= -154.291)
# Station 46076 Cape Cleare
CC <- data.frame(lat=59.502, long= -147.990)
  
# palette:
colMap <- c("dimgrey","black")

colors <- c("blue3","turquoise2","deepskyblue","royalblue1","violet","thistle1",
            "darkseagreen","greenyellow","olivedrab3",
            "coral","tomato3","orangered4","rosybrown1","hotpink1",
            "yellow","goldenrod1","tan2")
```

```{r, echo=FALSE, fig.height=12, fig.width=12}
# Map plot:
 ggplot(data=stateDf, aes(y=lat, x=long)) +
        geom_map(map=stateDf,aes(x=long,y=lat,map_id=id)) +
        coord_map(xlim = c(-155.5, -144),ylim = c(57.5, 62)) + 
        scale_fill_manual(values=colMap) +
        labs(x = "Longitude", y = "Latitude") +
        geom_point(data=BenNear1, aes(x=as.numeric(Long), y=as.numeric(Lat),
                                      shape=Region), size=3, stroke=1.75, color="#E066FF") + 
        geom_point(data=GAK1_loc, aes(long, lat), colour="black", fill="#C0FF3E",
                   size=4, stroke=1, shape=24) +  # this is GAK1
        annotate("text", x=-149, y=59.8, label="GAK1", size=5) +
        #geom_point(data=WOB, aes(long, lat), colour="black", fill="yellow",
        #           size=4, shape=24) + # this is West Orca Bay (PWS)
        #geom_point(data=SS, aes(long, lat), colour="black", fill="yellow", 
        #           size=4, shape=24) + # this is Shelikof Strait (KATM)
        #geom_point(data=CC, aes(long, lat), colour="black", fill="yellow", 
        #           size=4, shape=24) + # this is Cape Cleare (KEFJ)
        scale_shape_manual(values=c(15,24,8),
                           breaks=c("KATM","KEFJ","WPWS")) +
        theme(axis.line=element_line('black'),
              axis.text=element_text(size=15),
              axis.title=element_text(size=17),
              panel.grid.major=element_blank(),
              panel.grid.minor=element_blank(),
              panel.border=element_blank(),
              panel.background=element_blank(),
              plot.margin=unit(c(0.5,0.5,0.5,0.5), "cm"),
              legend.key = element_blank(),
              legend.text=element_text(size=17),
              legend.title=element_blank(),
              legend.position = c(.9, .2)) 

                # scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"), 
                #                   breaks=c("KATM", "KEFJ", "WPWS"),
                #                  labels=c("Katmai", " Kenai", "Prince William /n Sound")) +

```


```{r, echo=FALSE, include=FALSE}
# make Yes/No for sample presence
melt_BenNear2 <- reshape::melt.data.frame(as.data.frame(BenNear2), id.vars=c("Year","Region","Site_Name"),      
                      variable_name="Data_Set")

BenNear3 <- melt_BenNear2 %>%
            mutate(Bin_Value = ifelse((is.na(value)),'0',
                               ifelse((!is.na(value)),'1',""))) %>%
           # dplyr::rename(DataSet=variable) %>%
            mutate_each(funs(as.character), Site_Name) %>%
            mutate_each(funs(as.character), Data_Set)

BenNear4 <- BenNear3 %>%
            filter(Data_Set %in%
                     c("Leukoma_MnBmss_gWW","Macoma_MnBmss_gWW",
                       "Saxidomus_MnBmss_gWW")) %>%
            mutate_each(funs(as.numeric), Bin_Value) %>%
            group_by(Year, Region, Site_Name) %>%
            summarise(BinValue2 = sum(Bin_Value)) %>%
            ungroup() %>%
            mutate(Data_Set = "Clam_Bmss_gWW")

BenNear5 <- BenNear3 %>%
            filter(Data_Set %in%
                     c("SOf_CrabSumBmss_gWW","SOf_ClamSumBmss_gWW","SOf_UrchinSumBmss_gWW",
                       "SOf_MusselSumBmss_gWW")) %>%
            mutate_each(funs(as.numeric), Bin_Value) %>%
            group_by(Year, Region, Site_Name) %>%
            summarise(BinValue2 = sum(Bin_Value)) %>%
            ungroup() %>%
            mutate(Data_Set = "SeaOttForage_Bmss_gWW")

BenNear6 <- BenNear3 %>%
            filter(Data_Set %in% c("Bare_Sub_Per_Cov","barnacle_Per_Cov","mussel_Per_Cov",
                                  "Fuc_dist_Per_Cov","Ala_marg_Per_Cov",
                                  "Neo_Odon_sp_Per_Cov","Brwn_alg_ann_Per_Cov",
                                  "Green_alg_ann_Per_Cov","Red_alg_ann_Per_Cov",
                                  "Red_alg_per_Per_Cov")) %>%
            mutate_each(funs(as.numeric), Bin_Value) %>%
            group_by(Year, Region, Site_Name) %>%
            summarise(BinValue2 = sum(Bin_Value)) %>%
            ungroup() %>%
            mutate(Data_Set = "Intertidal_Per_Cov")
  
BenNear7 <- BenNear3 %>%
            filter(!(Data_Set %in%
                       c("Leukoma_MnBmss_gWW","Macoma_MnBmss_gWW","Saxidomus_MnBmss_gWW",
                         "SOf_CrabSumBmss_gWW","SOf_ClamSumBmss_gWW",
                         "SOf_UrchinSumBmss_gWW","SOf_MusselSumBmss_gWW",
                         "Bare_Sub_Per_Cov","barnacle_Per_Cov","mussel_Per_Cov",
                         "Fuc_dist_Per_Cov","Ala_marg_Per_Cov",
                         "Neo_Odon_sp_Per_Cov","Brwn_alg_ann_Per_Cov",
                         "Green_alg_ann_Per_Cov","Red_alg_ann_Per_Cov",
                         "Red_alg_per_Per_Cov","SOf_CrabPropBmss","SOf_ClamPropBmss",
                         "SOf_UrchinPropBmss","SOf_MusselPropBmss",
                         "SOf_StarPropBmss","SOf_SnailPropBmss",
                         "SOf_ChitonPropBmss","SOf_OctopusPropBmss","SOf_WormPropBmss",
                         "SOf_OtherPropBmss","Leukoma_Abun_m2","Leukoma_MnSize_mm",
                         "Macoma_Abun_m2","Macoma_MnSize_mm",
                         "Saxidomus_Abun_m2","Saxidomus_MnSize_mm"))) 
           
BenNear8 <- bind_rows(BenNear7,BenNear4) 
BenNear9 <- bind_rows(BenNear8,BenNear5)
BenNear10 <- bind_rows(BenNear9,BenNear6)

BenNear11 <- BenNear10 %>%
             mutate(Bin_Value = as.numeric(Bin_Value),
                    BinValue2 = as.numeric(BinValue2),
                    BinValue3 = ifelse(is.na(Bin_Value), BinValue2, Bin_Value),
                    BinValue3 = ifelse(BinValue3 > 0, 1, BinValue3),
                    Region_Site = paste(Region, Site_Name, sep=":")) %>%
             arrange(Region_Site, Year)

```


```{r, eval=FALSE, include=FALSE, echo=FALSE, fig.height=14, fig.width=18}
##Plot 1: Data presence for all Regions, all Sites we have in hand to date

p <- ggplot(data=BenNear11, aes(x=Site_Name, y=Year)) + 
            geom_tile(aes(fill = as.factor(BinValue3)), colour = "white") +
            scale_fill_manual(breaks=c("0", "1"), values=c("gray", "green"), guide=FALSE) +
            scale_y_reverse() + facet_wrap(~Data_Set) +
            theme(axis.text.x = element_text(angle=90, vjust=1, hjust=1, 
                                             color="black", size=11),
                  axis.text.y = element_text(color="black", size=15),
                  axis.title  = element_text(face="bold", size=20))
p


```


```{r, echo=FALSE, fig.height=14, fig.width=18}
###Plot 2: Data presence for only Regions WPWS, KEFJ, KATM
# Only include Regions WPWS, KEFJ, KATM

BenNear12 <- BenNear11 %>%
             filter(Year %in% c(2006:2015),
                    Region %in% c("WPWS","KATM","KEFJ"), 
                    !(Site_Name %in% c("Northwest Bay", "Herring Bay-Southwest", "Herring Bay-Bear Cove",
                                       "Ninagiak Island", "Disk Island")),
                    Data_Set %in% c("ENSO_anul_mn","PDO_anul_mn","NPGO_anul_mn","UpWelAnom_anul_mn",
                                    "WaterTmp_C_AnnMn","TotChlA_micgL_AnnMn","Whelk_Sum_n_m2",
                                    "BLOYAdult_breed_n","SOtt_AnnMnEngRec","WaterTmp_WinterAnom",
                                    "SC_Mn_FWDisc_AnMn","Intertidal_Per_Cov")) %>%
             arrange(Region_Site, Year)

BenNear12$Data_Set = factor(BenNear12$Data_Set, levels=c("ENSO_anul_mn","PDO_anul_mn",
                                                         "NPGO_anul_mn","UpWelAnom_anul_mn",
                                                         "SC_Mn_FWDisc_AnMn", "WaterTmp_C_AnnMn",
                                                         "WaterTmp_WinterAnom","TotChlA_micgL_AnnMn",
                                                         "SOtt_AnnMnEngRec","BLOYAdult_breed_n",
                                                         "Whelk_Sum_n_m2", "Intertidal_Per_Cov"))

p15 <- ggplot(data=BenNear12, aes(x=Region_Site, y=Year)) + 
              geom_tile(aes(fill = as.factor(BinValue3)), colour = "white") +
              scale_fill_manual(breaks=c("0", "1"), values=c("gray", "green"), guide=FALSE) +
              scale_y_reverse(breaks=c(2007,2009,2011,2013,2015)) + facet_wrap(~Data_Set) +
              theme(axis.text.x = element_text(angle=90, vjust=1, hjust=1, 
                                               color="black", size=11),
                    axis.text.y = element_text(color="black", size=13),
                    axis.title  = element_text(face="bold", size=20))
p15


```


```{r, eval=FALSE, include=FALSE, echo=FALSE, fig.height=14, fig.width=18}
###Plot 3: Data presence for WPWS, KEFJ, KATM presented another way

p16 <- ggplot(data=BenNear12, aes(x=DataSet, y=Year)) + 
              geom_tile(aes(fill = as.factor(BinValue3)), colour = "white") +
              scale_fill_manual(breaks=c("0", "1"), values=c("gray", "green"), guide=FALSE) +
              scale_y_reverse() + facet_wrap(~Region_Site) +
              theme(axis.text.x = element_text(angle=90, vjust=1, hjust=1, 
                                               color="black", size=11),
                    axis.text.y = element_text(color="black", size=15),
                    axis.title  = element_text(face="bold", size=20))
p16

```


###Correlation pair plots of raw data: 
```{r, echo=FALSE, fig.height=14, fig.width=14}

library(psych)
BenNear2 <- as.data.frame(BenNear2)

# ENSO, NPGO, Upwelling, Hobo water temp, buoy water temp, winter water temp anomaly
pairs.panels(BenNear2[,c(4,10,11,14,15,17)],smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T) 

# chla, barnacles, mussels, hobo water temp
pairs.panels(BenNear2[,c(21,24,25,14)],smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

# mussels, fucus, total red algae, brown algae, green algae, hobo water temp
pairs.panels(BenNear2[,c(25,26,33,29,30,14)],smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

# hobo water temp, mussels, bloy adults, sea otter energy rec., freshwater discharge
pairs.panels(BenNear2[,c(14,25,34,35,38)],smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T) 

# upwelling, sea otter energy rec., freshwater discharge, hobo water temp, buoy water temp, chla
pairs.panels(BenNear2[,c(11,35,36,14,15,21)],smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T) 

# ENSO, PDO, mussels, NPGO, Upwelling
pairs.panels(BenNear2[,c(4,7,25,10,11)],smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

# upwelling, hobo water temp, buoy water temp, fw discharge
pairs.panels(BenNear2[,c(11,14,15,38)],smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

```



# Plot variables through time:
```{r, echo=FALSE}
BenNear_mus <- BenNear %>%
               filter(Year %in% c(2006:2015),
                      Region %in% c("WPWS","KATM","KEFJ"), 
                      !(Site_Name %in% c("Northwest Bay", "Herring Bay-Southwest", "Herring Bay-Bear Cove",
                                         "Ninagiak Island", "Disk Island"))) %>%
                select(Year, Region, ENSO_anul_mn, PDO_anul_mn, NPGO_anul_mn, UpWelAnom_anul_mn,
                       WaterTmp_C_AnnMn, TotChlA_micgL_AnnMn, Whelk_Sum_n_m2,
                       BLOYAdult_breed_n, SOtt_AnnMnEngRec, WaterTmp_WinterAnom,
                       Hobo_WaterTemp_AnnMn, FWDisc_MeanYearly_ft3s1) %>%
               arrange(Region, Year) %>%
              # na.omit() %>%
               filter(!is.na(WaterTmp_C_AnnMn)) %>%
               group_by(Year, Region) %>%
               summarize_each(funs(mean)) %>%
               ungroup()  
            
```


```{r, echo=FALSE}
#Plot_Vars <- function(datafr, Resp){
#             p19 <- ggplot(data=datafr, aes(x=SiteName, y=Resp)) + 
#                    geom_line()
#             return(p19)
#}



ggplot(data=BenNear_mus, aes(x=Year, y=WaterTmp_C_AnnMn)) + 
               geom_line(size=2) + facet_wrap(~Region) + 
               theme(axis.text.x = element_text(angle=90, vjust=0.5, hjust=1, 
                                                color="black", size=11),
                     axis.text.y = element_text(color="black", size=15),
                     axis.title  = element_text(face="bold", size=20))

```



```{r, echo=FALSE, eval=FALSE}
BenNear_sub2 <- BenNear %>%
                filter(Region %in% c("WPWS","KATM","KEFJ")) %>%
               # na.omit() %>%
                filter(!is.na(mussel_Per_Cov)) %>%
                select(-Quadrat, -Lat,-Long) %>%
                mutate_each(funs(as.numeric), Otter_Abun_est) %>%
                group_by(Year, Region, Site_Name) %>%
                summarize_each(funs(mean)) %>%
                ungroup()  
            
```

```{r, echo=FALSE, eval=FALSE}

ggplot(data=BenNear12, aes(x=Year, y=mussel_Per_Cov)) + 
               geom_line(size=2) + facet_wrap(~Site_Name) + 
               theme(axis.text.x = element_text(angle=90, vjust=1, hjust=1, 
                                               color="black", size=11),
                    axis.text.y = element_text(color="black", size=15),
                    axis.title  = element_text(face="bold", size=20))

```

```{r, eval=FALSE, echo=FALSE}
# LOAD and pre-process data for the mussel analysis
BenNearMUSS <- read.csv("BenthicNearshore_MusselQuestData.csv")

BenNearMUSS2 <- BenNearMUSS %>%
                select(-Quadrat, -Lat,-Long) %>%
                group_by(Year, Region, Site_Name) %>%
                summarize_each(funs(sum)) %>%
                ungroup()


```

```{r, eval=FALSE, echo=FALSE}
# make Yes/No for sample presence
melt_BenNearMUSS2 <- melt(as.data.frame(BenNearMUSS2), id.vars=c("Year","Region","Site_Name"),                                       variable_name="Data_Set")

BenNearMUSS3 <- melt_BenNearMUSS2 %>%
                mutate(Bin_Value = ifelse((is.na(value)),'0',
                                   ifelse((!is.na(value)),'1',""))) %>%
             #   dplyr::rename(variable=Data_Set) %>%
                mutate_each(funs(as.character), Site_Name) %>%
                mutate_each(funs(as.character), Data_Set) %>%
                mutate_each(funs(as.factor), Bin_Value) %>%
                filter(!(Region %in% c("NPWS", "EPWS", "LACL")))
  

```

```{r,eval=FALSE, echo=FALSE, fig.height=18, fig.width=18}
pm <- ggplot(data=BenNearMUSS3, aes(x=Site_Name, y=Year)) + 
             geom_tile(aes(fill = as.factor(Bin_Value)), colour = "white") +
             scale_fill_manual(breaks=c("0", "1"), values=c("gray", "green"), guide=FALSE) +
             scale_y_reverse() + facet_wrap(~Data_Set) +
             theme(axis.text.x = element_text(angle=90, vjust=1, hjust=1, 
                                              color="black", size=11),
                   axis.text.y = element_text(color="black", size=15),
                   axis.title  = element_text(face="bold", size=20))
pm
```

```{r,eval=FALSE, echo=FALSE, fig.height=18, fig.width=18}

pm2 <- ggplot(data=BenNearMUSS3, aes(x=Data_Set, y=Year)) + 
              geom_tile(aes(fill = as.factor(Bin_Value)), colour = "white") +
              scale_fill_manual(breaks=c("0", "1"), values=c("gray", "green"), guide=FALSE) +
              scale_y_reverse() + facet_wrap(~Site_Name) +
              theme(axis.text.x = element_text(angle=90, vjust=1, hjust=1, 
                                               color="black", size=11),
                    axis.text.y = element_text(color="black", size=15),
                    axis.title  = element_text(face="bold", size=20))
pm2


```

