---
title: "Mussels_LME_DMX_Benthic"
author: "Rachael Blake"
date: "September 12, 2016"
output: html_document
---

```{r, echo=FALSE, include=FALSE}

# load necessary packages
library(randomForest) ; library(plyr) ; library(dplyr) ; library(psych) ; library(nlme) ; library(ggplot2)
library(AICcmodavg)

# load data 
BenNearMuss <- read.csv("C:/Users/rblake/Documents/NCEAS/GoA Dynamics WG/dmx-drivers/BenthicNearshore_MusselQuestData.csv")

# call the data assembly script
#source("Benthic_Nearshore_Drivers/Benthic_Nearshore_Data_.R")
#head(BenNear)


```

```{r, echo=FALSE}
# filtering data for more complete dataset
BenNear_m <- BenNearMuss %>%
             filter(Year %in% c(2007:2013),
                    Region %in% c("WPWS","KATM","KEFJ")) %>%
             mutate_each(funs(as.numeric), Otter_Abun_est) %>%
             mutate(log_mussel_Per_Cov = log(mussel_Per_Cov+1),
                    log_SOf_MusselSumBmss_gWW = log(SOf_MusselSumBmss_gWW+1),
                    log_TotChlA_micgL_FlMn = log(TotChlA_micgL_FlMn+1),
                    log_TotChlA_micgL_AnnMn = log(TotChlA_micgL_AnnMn+1)) %>%
             select(-BLOY_MnDensity_km2, -TotChlA_micgL_SpMn)
       


```

```{r, echo=FALSE}
#### Manipulate data columns to add 1-year lags!!!!

#dplyr::lead
#Copy with values shifted by 1.
#dplyr::lag
#Copy with values lagged by 1.

BenNear_reg_l <- BenNear_m %>% 
                 select(-Site_Name,-Quadrat,-Lat,-Long) %>%
                 group_by(Year, Region) %>%
                 summarise_each(funs(mean(., na.rm=TRUE))) %>%
                 ungroup() %>%
                 arrange(Region, Year) %>%
                 group_by(Region) %>%
                 mutate(LAG_log_TotChlA_micgL_AnnMn = lag(log_TotChlA_micgL_AnnMn),
                        LAG_UpWelAnom_anul_mn = lag(UpWelAnom_anul_mn),
                        LED_SOf_MusselPropBmss = lead(SOf_MusselPropBmss),
                        LED_BLOYAdult_breed_n = lead(BLOYAdult_breed_n),
                        LAG_Bare_Sub_Per_Cov = lag(Bare_Sub_Per_Cov),
                        LAG_PDO_anul_mn = lag(PDO_anul_mn),
                        LAG_WndSp_m_s_AnnMn = lag(WndSp_m_s_AnnMn),
                        LAG_WndSp_m_s_Winter = lag(WndSp_m_s_Winter),
                        LAG_Fuc_dist_Per_Cov = lag(Fuc_dist_Per_Cov),
                        LAG_SC_Mn_FWDisc_AnMn = lag(SC_Mn_FWDisc_AnMn),
                        LAG_Ttl_FWDisc_Anom_AnMn = lag(Ttl_FWDisc_Anom_AnMn),
                        LAG_SC_Mn_FWDisc_SpMn = lag(SC_Mn_FWDisc_SpMn),
                        LAG_Ttl_FWDisc_Anom_SpMn = lag(Ttl_FWDisc_Anom_SpMn)) %>%
                 ungroup() 
               

# BenNear_GOA_l <- BenNear_m %>% 
#                  select(-Site_Name,-Quadrat,-Lat,-Long,-Region) %>%
#                  group_by(Year) %>%
#                  summarise_each(funs(mean(., na.rm=TRUE))) %>%
#                  ungroup() %>%
#                  arrange(Year) %>%
#                  mutate(LAG_log_TotChlA_micgL_AnnMn = lag(log_TotChlA_micgL_AnnMn),
#                         LAG_UpWelAnom_anul_mn = lag(UpWelAnom_anul_mn),
#                         LED_SOf_MusselPropBmss = lead(SOf_MusselPropBmss),
#                         LED_BLOYAdult_breed_n = lead(BLOYAdult_breed_n),
#                         LAG_Bare_Sub_Per_Cov = lag(Bare_Sub_Per_Cov),
#                         LAG_PDO_anul_mn = lag(PDO_anul_mn),
#                         LAG_WndSp_m_s_AnnMn = lag(WndSp_m_s_AnnMn),
#                         LAG_WndSp_m_s_Winter = lag(WndSp_m_s_Winter),
#                         LAG_Fuc_dist_Per_Cov = lag(Fuc_dist_Per_Cov),
#                         LAG_SC_Mn_FWDisc_AnMn = lag(SC_Mn_FWDisc_AnMn),
#                         LAG_Ttl_FWDisc_Anom_AnMn = lag(Ttl_FWDisc_Anom_AnMn),
#                         LAG_SC_Mn_FWDisc_SpMn = lag(SC_Mn_FWDisc_SpMn),
#                         LAG_Ttl_FWDisc_Anom_SpMn = lag(Ttl_FWDisc_Anom_SpMn))    


```

```{r, echo=FALSE}
# Function to create interaction plots of all variables
my_interactions <- function(dataframe,x,y,key){
                   # get a mean value for each Region
                   A <- dataframe %>%
                        group_by_(x,key) %>%
                        summarise_each_(funs(val=mean(., na.rm=TRUE)), y)
                   #return(A)
                   # make a plot
                   PT <- ggplot(data=dataframe, aes_string(x=x, y=y, colour=factor(key))) +
                         geom_point(data=A, aes(y=val)) + theme_bw() + 
                         geom_line(data=A, aes_string(y="val", group=key))
                   return(PT)
                   }
my_interactions(BenNear_reg_l, "LAG_log_TotChlA_micgL_AnnMn", "log_mussel_Per_Cov", "Region")


#trying this from a Stack Overflow answer
testplot <- function(meansdf){
            p <- ggplot(meansdf, aes(fill = condition, y = means, x = condition)) +
                 geom_bar(position = "dodge", stat = "identity")
}

aes_string(x="date", y=aesy) 

mtcars %>% 
     group_by(gear) %>% 
     summarise_each(funs(mean=mean(., na.rm=TRUE),
                     sd=sd(., na.rm=TRUE)), wt, qsec)


# My original attempt 
   A <- ddply(dataframe, .(x, key), summarise, val=mean(y, na.rm=TRUE))
# partial success
    A <- ddply(dataframe, c(x, key), summarise, val=mean(c(y), na.rm=TRUE))
    
   
# The manual way of doing things...   
# y=log_mussel_Per_Cov x=LAG_log_TotChlA_micgL_AnnMn key=Region
SgBM <- ddply(BenNear_reg_l, .(LAG_log_TotChlA_micgL_AnnMn,Region), summarise,
              val=mean(log_mussel_Per_Cov, na.rm=TRUE))  # this calculates a mean value at each bin
sb  <- ggplot(data=BenNear_reg_l, aes(x=LAG_log_TotChlA_micgL_AnnMn,
                                      y=log_mussel_Per_Cov, colour=factor(Region))) + 
       geom_point(data=SgBM, aes(y=val)) +  theme_bw() +
       geom_line(data=SgBM, aes(y=val, group=Region)) 


```



```{r, echo=FALSE}
#############################################################
### Selecting correct Random Effect structure for data,   ###
### following example from Zuur Mixed Effects Models book ###
#############################################################
# Possible predictor variables in the model:
# Year, Region, ENSO_anul_mn, PDO_anul_mn, NPGO_anul_mn, UpWelAnom_anul_mn, WaterTmp_C_AnnMn, 
# WndDir_degT_AnnMn, WndSp_m_s_AnnMn, TotChlA_micgL_AnnMn, Bare_Sub_Per_Cov, Fuc_dist_Per_Cov, 
# BLOYAdult_breed_n, SOf_MusselSumBmss_gWW, SOf_MusselPropBmss, SOtt_AnnMnEngRec, WaterTmp_WinterAnom,
# Ttl_FWDisc_Anom_AnMn, log_mussel_Per_Cov, log_SOf_MusselSumBmss_gWW, log_TotChlA_micgL_FlMn,
# log_TotChlA_micgL_AnnMn, LAG_log_TotChlA_micgL_AnnMn, LAG_UpWelAnom_anul_mn, LED_SOf_MusselPropBmss,
# LED_BLOYAdult_breed_n, LAG_PDO_anul_mn, LAG_WndSp_m_s_AnnMn, LAG_WndSp_m_s_Winter, LAG_SC_Mn_FWDisc_AnMn,
# LAG_Ttl_FWDisc_Anom_AnMn, LAG_SC_Mn_FWDisc_SpMn, LAG_Ttl_FWDisc_Anom_SpMn 

# checking out heterogeneity
boxplot(log_mussel_Per_Cov ~ Year, data=BenNear_reg_l)

# Models
mgls1 <- gls(log_mussel_Per_Cov ~ Year+LAG_UpWelAnom_anul_mn+
             LAG_log_TotChlA_micgL_AnnMn+ENSO_anul_mn+LAG_WndSp_m_s_AnnMn+
             LAG_Ttl_FWDisc_Anom_AnMn, 
             # LAG_log_TotChlA_micgL_AnnMn:LAG_Ttl_FWDisc_Anom_AnMn, 
             na.action=na.exclude, data=BenNear_reg_l)

# random intercept model, allows for variation between Regions
mlme1 <- lme(log_mussel_Per_Cov ~ Year+LAG_UpWelAnom_anul_mn+LAG_log_TotChlA_micgL_AnnMn+
             ENSO_anul_mn+LAG_WndSp_m_s_AnnMn+LAG_Ttl_FWDisc_Anom_AnMn,
             random=~1|Region, na.action=na.exclude, data=BenNear_reg_l)

anova(mgls1, mlme1)   
# this corrects the p-value for the difference between the two models
0.5*(1-pchisq(6.093615e-11,1))  # formula is 0.5*(1-pchisq(L.Ratio,1))

# Freshwater Discharge effect may be different per Region
mlme2 <- lme(log_mussel_Per_Cov ~ Year+LAG_UpWelAnom_anul_mn+LAG_log_TotChlA_micgL_AnnMn+
             ENSO_anul_mn+LAG_WndSp_m_s_AnnMn+LAG_Ttl_FWDisc_Anom_AnMn,
             random=~1+LAG_Ttl_FWDisc_Anom_AnMn|Region, na.action=na.exclude, data=BenNear_reg_l)
anova(mlme1, mlme2)

# Adding in variance structure to mlme2
#mlme3 <- lme(log_mussel_Per_Cov ~ Year+LAG_UpWelAnom_anul_mn+LAG_log_TotChlA_micgL_AnnMn+
#             ENSO_anul_mn+LAG_WndSp_m_s_AnnMn+LAG_Ttl_FWDisc_Anom_AnMn,
#             random=~1+LAG_Ttl_FWDisc_Anom_AnMn|Region, weights=varIdent(form=~1|Region),
#             na.action=na.exclude, data=BenNear_reg_l)
#anova(mlme1, mlme3)

# Adding variance structure to mlme1
mlme4 <- lme(log_mussel_Per_Cov ~ Year+LAG_UpWelAnom_anul_mn+LAG_log_TotChlA_micgL_AnnMn+
             ENSO_anul_mn+LAG_WndSp_m_s_AnnMn+LAG_Ttl_FWDisc_Anom_AnMn,
             random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
             data=BenNear_reg_l)
anova(mlme1, mlme4)


# mlme4 is it

```

```{r, echo=FALSE}
#################################################################
## Selecting the fixed variable structure:                     ##
## Global and alternate doubly-nested models with interactions ##
## Models developed a-priori based on ecological principles    ##
#################################################################
## Factor A (Main treatment factor): Region (random factor)
## Possible predictor variables in the model: 
##    
## Interactions to include (based on interaction plots above): 
##    

# Mussel cover Everything Model
MGM <- lme(log_mussel_Per_Cov ~ Year+LAG_UpWelAnom_anul_mn+LAG_log_TotChlA_micgL_AnnMn+
           ENSO_anul_mn+LAG_WndSp_m_s_AnnMn+LAG_Ttl_FWDisc_Anom_AnMn,
           random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
           data=BenNear_reg_l, method="ML")

# Mussel cover Climate
Mcl <- lme(log_mussel_Per_Cov ~ Year+LAG_UpWelAnom_anul_mn+ENSO_anul_mn,
           random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
           data=BenNear_reg_l, method="ML")

# Mussel cover Wind Freshwater Chla
Mfc <- lme(log_mussel_Per_Cov ~ Year+LAG_log_TotChlA_micgL_AnnMn+
                                LAG_WndSp_m_s_AnnMn+LAG_Ttl_FWDisc_Anom_AnMn,
           random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
           data=BenNear_reg_l, method="ML")

# Mussel cover Freshwater 
Mfw <- lme(log_mussel_Per_Cov ~ Year+LAG_Ttl_FWDisc_Anom_AnMn,
           random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
           data=BenNear_reg_l, method="ML")

# Mussel cover Chla
Mcc <- lme(log_mussel_Per_Cov ~ Year+LAG_log_TotChlA_micgL_AnnMn,
           random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
           data=BenNear_reg_l, method="ML")

# Mussel cover Wind
Mww <- lme(log_mussel_Per_Cov ~ Year+LAG_WndSp_m_s_AnnMn,
           random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
           data=BenNear_reg_l, method="ML")


AIC(MGM, Mcl, Mfc, Mfw, Mcc, Mww)
Cand_Mod <- list(MGM, Mcl, Mfc, Mfw, Mcc, Mww)
Modnames <- c("MGM", "Mcl", "Mfc", "Mfw", "Mcc", "Mww")
aictab(Cand_Mod, Modnames, sort=TRUE, second.ord=TRUE)

# MGM and Mfc are tied, so choose Mfc as simpler model

# Re-fit the chosen model using REML
Mfr <- lme(log_mussel_Per_Cov ~ Year+LAG_log_TotChlA_micgL_AnnMn+
                                LAG_WndSp_m_s_AnnMn+LAG_Ttl_FWDisc_Anom_AnMn,
           random=~1|Region, weights=varIdent(form=~1|Region), na.action=na.exclude, 
           data=BenNear_reg_l, method="REML")

summary(Mfr)
anova(Mfr)
plot(Mfr)

```


```{r, echo=FALSE}
## Coefficient of variation for Regions
names(BenNear_reg_l)
co_var <- function(x) ( 100*sd(x)/mean(x) )   # function for calculating CV

mcv_wpws <- BenNear_reg_l[BenNear_reg_l$Region=="WPWS",c(38)]
co_var(mcv_wpws)

mcv_kefj <- BenNear_reg_l[BenNear_reg_l$Region=="KEFJ",c(38)]  
co_var(mcv_kefj)  

mcv_katm <- BenNear_reg_l[BenNear_reg_l$Region=="KATM",c(38)]  
co_var(mcv_katm)  

```

```{r, echo=FALSE}
#############################################################
### Selecting correct Random Effect structure for data,   ###
### following example from Zuur Mixed Effects Models book ###
#############################################################
# Possible predictor variables in the model:
# Year, Region, ENSO_anul_mn, PDO_anul_mn, NPGO_anul_mn, UpWelAnom_anul_mn, WaterTmp_C_AnnMn, 
# WndDir_degT_AnnMn, WndSp_m_s_AnnMn, TotChlA_micgL_AnnMn, Bare_Sub_Per_Cov, Fuc_dist_Per_Cov, 
# BLOYAdult_breed_n, SOf_MusselSumBmss_gWW, SOf_MusselPropBmss, SOtt_AnnMnEngRec, WaterTmp_WinterAnom,
# Ttl_FWDisc_Anom_AnMn, log_mussel_Per_Cov, log_SOf_MusselSumBmss_gWW, log_TotChlA_micgL_FlMn,
# log_TotChlA_micgL_AnnMn, LAG_log_TotChlA_micgL_AnnMn, LAG_UpWelAnom_anul_mn, LED_SOf_MusselPropBmss,
# LED_BLOYAdult_breed_n, LAG_PDO_anul_mn, LAG_WndSp_m_s_AnnMn, LAG_WndSp_m_s_Winter, LAG_SC_Mn_FWDisc_AnMn,
# LAG_Ttl_FWDisc_Anom_AnMn, LAG_SC_Mn_FWDisc_SpMn, LAG_Ttl_FWDisc_Anom_SpMn 

# Models
mgls12 <- gls(log_mussel_Per_Cov ~ Region+Year+WaterTmp_C_AnnMn+WaterTmp_SpringAnom+
                                   Bare_Sub_Per_Cov+SOf_MusselPropBmss+BLOYAdult_breed_n+
                                   Fuc_dist_Per_Cov,
              na.action=na.exclude, data=BenNear_reg_l)

# random intercept model, allows for variation between Regions
mlme12 <- lme(log_mussel_Per_Cov ~ Year+WaterTmp_C_AnnMn+WaterTmp_SpringAnom+
                                   Bare_Sub_Per_Cov+SOf_MusselPropBmss+BLOYAdult_breed_n+
                                   Fuc_dist_Per_Cov,
              random=~1|Region, na.action=na.exclude, data=BenNear_reg_l)

anova(mgls12, mlme12)   
# this corrects the p-value for the difference between the two models
0.5*(1-pchisq(6.093615e-11,1))  # formula is 0.5*(1-pchisq(L.Ratio,1))

mlme22 <- lme(log_mussel_Per_Cov ~ Year+WaterTmp_C_AnnMn+WaterTmp_SpringAnom+
                                   Bare_Sub_Per_Cov+SOf_MusselPropBmss+BLOYAdult_breed_n+
                                   Fuc_dist_Per_Cov,
              random=~1+Bare_Sub_Per_Cov|Region, na.action=na.exclude, data=BenNear_reg_l)

anova(mlme12, mlme22)  

mlme32 <- lme(log_mussel_Per_Cov ~ Year+WaterTmp_C_AnnMn+WaterTmp_SpringAnom+Bare_Sub_Per_Cov+ 
                                   SOf_MusselPropBmss+BLOYAdult_breed_n+Fuc_dist_Per_Cov,
              random=~1+Bare_Sub_Per_Cov|Region, weights=varIdent(form=~1|Region),
              na.action=na.exclude, data=BenNear_reg_l)

anova(mlme22, mlme32) 

mlme42 <- lme(log_mussel_Per_Cov ~ Year+WaterTmp_C_AnnMn+WaterTmp_SpringAnom+Bare_Sub_Per_Cov+ 
                                   SOf_MusselPropBmss+BLOYAdult_breed_n+Fuc_dist_Per_Cov,
              random=~1|Region, weights=varIdent(form=~1|Region),
              na.action=na.exclude, data=BenNear_reg_l)

anova(mlme32, mlme42) 
anova(mlme12, mlme22, mlme32, mlme42)

# nothing is better than the mlme12 model, so choosing that

```

```{r, echo=FALSE}

```

