---
title: "Random_Forest_Explore_DMX_Benthic"
author: "Rachael Blake"
date: "April 1, 2016"
output: html_document
---

```{r, echo=FALSE, include=FALSE}

# load necessary packages
library(randomForest) ; library(plyr) ; library(dplyr) ; library(psych)

# load data 
BenNearMuss <- read.csv("C:/Users/rblake/Documents/NCEAS/GoA Dynamics WG/dmx-drivers/BenthicNearshore_MusselQuestData.csv")

# call the data assembly script
#source("Benthic_Nearshore_Drivers/Benthic_Nearshore_Data_.R")
#head(BenNear)

# filter data for complete cases
BenNear4 <- BenNearMuss %>%
            select(-BLOY_MnDensity_km2) %>%
            select(which(colMeans(is.na(.)) < 0.5)) %>%
            filter(complete.cases(.))

```

```{r, echo=FALSE}
BenNear_m <- BenNearMuss %>%
             mutate(log_mussel_Per_Cov = log(mussel_Per_Cov+1),
                    log_SOf_MusselSumBmss_gWW = log(SOf_MusselSumBmss_gWW+1),
                    log_TotChlA_micgL_SpMn = log(TotChlA_micgL_SpMn+1),
                    log_TotChlA_micgL_FlMn = log(TotChlA_micgL_FlMn+1),
                    log_TotChlA_micgL_AnnMn = log(TotChlA_micgL_AnnMn+1)
                    ) 
             
#### Manipulate data columns to add lags!!!!

#dplyr::lead
#Copy with values shifted by 1.
#dplyr::lag
#Copy with values lagged by 1.

```



```{r, echo=FALSE}
# Define some functions

# Important variables are greater than the absolute value of the most negative
# importance value.
Imp_Var <- function(rf_obj){
           a <- data.frame(rf_obj$importance)  
           b <- min(a[,1])  # smallest value
           c <- abs(b)  # absolute value of smallest value
           d <- a$X.IncMSE[a$X.IncMSE>c]  # numbers great than absolute value of smallest value
           return(d)
           }


```


```{r, echo=FALSE}
# subset the dataframe and get means and 1-year lags

BenNear_reg <- BenNear_m %>% 
               mutate_each(funs(as.numeric), Otter_Abun_est) %>%
               filter(Region %in% c("WPWS","KATM","KEFJ"),
                      Year %in% c(2000:2015)) %>%
               select(-Site_Name,-Quadrat,-Lat,-Long) %>%
               group_by(Year, Region) %>%
               summarise_each(funs(mean(., na.rm=TRUE))) %>%
               ungroup() %>%
               arrange(Region, Year) %>%
               group_by(Region) %>%
               mutate(LAG_log_TotChlA_micgL_AnnMn = lag(log_TotChlA_micgL_AnnMn),
                      LAG_UpWelAnom_anul_mn = lag(UpWelAnom_anul_mn),
                      LED_SOf_MusselPropBmss = lead(SOf_MusselPropBmss),
                      LED_BLOYAdult_breed_n = lead(BLOYAdult_breed_n),
                      LAG_Bare_Sub_Per_Cov = lag(Bare_Sub_Per_Cov),
                      LAG_PDO_anul_mn = lag(PDO_anul_mn),
                      LAG_WndSp_m_s_AnnMn = lag(WndSp_m_s_AnnMn),
                      LAG_WndSp_m_s_Winter = lag(WndSp_m_s_Winter),
                      LAG_Fuc_dist_Per_Cov = lag(Fuc_dist_Per_Cov)) %>%
               ungroup() 
               

BenNear_GOA <- BenNear_m %>% 
               mutate_each(funs(as.numeric), Otter_Abun_est) %>%
               filter(Region %in% c("WPWS","KATM","KEFJ"),
                      Year %in% c(2000:2015)) %>%
               select(-Site_Name,-Quadrat,-Lat,-Long,-Region) %>%
               group_by(Year) %>%
               summarise_each(funs(mean(., na.rm=TRUE))) %>%
               ungroup() %>%
               arrange(Year) %>%
               mutate(LAG_log_TotChlA_micgL_AnnMn = lag(log_TotChlA_micgL_AnnMn),
                      LAG_UpWelAnom_anul_mn = lag(UpWelAnom_anul_mn),
                      LED_SOf_MusselPropBmss = lead(SOf_MusselPropBmss),
                      LED_BLOYAdult_breed_n = lead(BLOYAdult_breed_n),
                      LAG_Bare_Sub_Per_Cov = lag(Bare_Sub_Per_Cov),
                      LAG_PDO_anul_mn = lag(PDO_anul_mn),
                      LAG_WndSp_m_s_AnnMn = lag(WndSp_m_s_AnnMn),
                      LAG_WndSp_m_s_Winter = lag(WndSp_m_s_Winter),
                      LAG_Fuc_dist_Per_Cov = lag(Fuc_dist_Per_Cov))  


```



```{r, echo=FALSE}
###
# Mussels 
Muss_rf <- BenNear_GOA[,c(5,8,9,12,14,15,21,24,27,30,33,34,37)]#

Muss_lg <- BenNear_reg[,c(6,9,10,13,15,16,22,25,28,31,34,35,38)]#

LAG_Muss_rf <- BenNear_GOA[,c(8,12,14,30,33,34,38:46)]#

LAG_Muss_lg <- BenNear_reg[,c(9,13,15,31,34,39:47)]#

```


```{r, echo=FALSE, fig.height=18, fig.width=18}

pairs.panels(Muss_rf,smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

pairs.panels(LAG_Muss_rf,smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

pairs.panels(Muss_lg,smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

pairs.panels(LAG_Muss_lg,smooth=F,density=T,ellipses=F,lm=T,digits=3,scale=T)

```

#### Calculate lags of 1 year for environmental variables 



